config/routes.rb
Rails.application.routes.draw do
  get 'promote_activities/index'
  get 'pages/index'
  get 'user_page/:user_id', to: 'pages#user_page', as: 'user_page'

  post 'activity/:user_id', to: 'user_activities#create', as: 'asigne_activity'
  get 'edit/:user_id/:activity_id', to: 'user_activities#edit', as: 'edit_activity'
  delete 'activity/:user_id/:activity_id', to: 'user_activities#destroy', as: 'destroy_activity'
  patch 'edit/:user_id/:activity_id', to: 'user_activities#update', as: 'update_activity'

  post 'new_activity/:user_id', to: 'activities#create', as: 'new_activity'
  get 'edit_new_user_activity/:user_id/:activity_id', to: 'activities#edit', as: 'edit_new_user_activity'
  patch 'update_new_activity/:activity_id', to: 'activities#update', as: 'update_new_activity'
  
  get 'promote_activities/:user_id', to: 'promote_activities#index', as: 'promote_activities'
  get 'new_promote', to: 'promote_activities#new', as: 'new_promote'
  post 'create_promote/:user_id', to: 'promote_activities#create', as: 'create_promote'
  delete 'promote/:id', to: 'promote_activities#destroy', as: 'destroy_promote'

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/promote_activity.rb
class PromoteActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  belongs_to :billing, optional: true

  attribute :payed, :boolean, default: false

end

app/controllers/promote_activities_controller.rb
class PromoteActivitiesController < ApplicationController
  authorize_resource

  def index
  	@user = User.find(params[:user_id])
  	@promotes = PromoteActivity.where(user_id: params[:user_id])
  end

  def new
    @activities = Activity.all
  	@promote_activity = PromoteActivity.new
  end

  def create
    @promote_activity = PromoteActivity.new
    @promote_activity.user_id = params[:user_id]
    @promote_activity.activity_id = params[:promote_activity][:activity_id]
    @promote_activity.amount = params[:promote_activity][:amount]
    @promote_activity.save
    redirect_to promote_activities_path(current_user)
  end

  def destroy
    #@promote_activity = PromoteActivity.where(user_id: params[:user_id], activity_id: params[:activity_id]).first
    @promote_activity = PromoteActivity.find(params[:id])
    @promote_activity.destroy
    redirect_to promote_activities_path(current_user), notice: 'La promoción fue eliminada'
  end

end

app/helpers/promote_activities_helper.rb
module PromoteActivitiesHelper
end

app/views/promote_activities/index.html.erb
<h3>Promociones de <%= @user.name %></h3><br>

<table class="table">
	<thead>
		<th>Producto</th>
		<th>Precio</th>
		<th>¿Pagada?</th>
		<th></th>
	</thead>
		<tbody>
		<% @promotes.each do |promote| %>
			<tr>
				<td><%= promote.activity.name %></td>
				<td><%= promote.amount %></td>
				<td>
					<% if promote.payed? %>
						Pagado
					<% else %>
						Pendiente de pago
					<% end %>
				</td>
				<td>
					<% if promote.payed? %>
					<% else %>
						<%= link_to 'Borrar promoción', destroy_promote_path(promote.id), method: :delete %>
					<% end %>	
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<td><%= link_to 'Promocionar Todo', pre_pay_billings_path, :class => 'btn btn-sm btn-success float-right' %>

app/views/promote_activities/new.html.erb
<h3>Crear Promociones de <%= current_user.name %></h3><br>

<h5>Elija una actividad a promocionar</h5>

<% if user_signed_in? %>
	<%= form_with model: @promote_activity, url: create_promote_path(current_user.id), method: :post, local: true do |f| %>

		<%= f.label :activity %>
		<%= f.collection_select :activity_id, @activities, :id, :name, :prompt => true %><br>

		<%= f.label :monto_a_promocionar %>
		<%= f.number_field :amount, :class => 'text_field', :step => 0.5 %><br>

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>