config/routes.rb
Rails.application.routes.draw do
  get 'promote_activities/index'
  get 'pages/index'
  get 'user_page/:user_id', to: 'pages#user_page', as: 'user_page'

  post 'activity/:user_id', to: 'user_activities#create', as: 'asigne_activity'
  get 'edit/:user_id/:activity_id', to: 'user_activities#edit', as: 'edit_activity'
  delete 'activity/:user_id/:activity_id', to: 'user_activities#destroy', as: 'destroy_activity'
  patch 'edit/:user_id/:activity_id', to: 'user_activities#update', as: 'update_activity'

  post 'new_activity/:user_id', to: 'activities#create', as: 'new_activity'
  get 'edit_new_user_activity/:user_id/:activity_id', to: 'activities#edit', as: 'edit_new_user_activity'
  patch 'update_new_activity/:activity_id', to: 'activities#update', as: 'update_new_activity'
  
  get 'promote_activities/:user_id', to: 'promote_activities#index', as: 'promote_activities'
  get 'new_promote', to: 'promote_activities#new', as: 'new_promote'
  post 'create_promote/:user_id', to: 'promote_activities#create', as: 'create_promote'
  delete 'promote/:id', to: 'promote_activities#destroy', as: 'destroy_promote'

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/index.html.erb
<h1>Pages#index</h1>


<% if user_signed_in? %>
	<%= form_with model: @activity, url: asigne_activity_path(current_user), method: :post, local: true do |f| %>

		<%= f.label :activity %>
		<%= f.collection_select :activity_id, @user_activities, :id, :name, :prompt => true %>

		<%= f.submit "Enviar" %>

	<% end %><br>

	<%= form_with model: @activity, url: new_activity_path(current_user), method: :post, local: true do |f| %>
	
		<%= f.label :nueva_actividad %>
		<%= f.text_field :name %>

		<%= f.submit "Enviar" %>
	<% end %><br>



<% end %>

<br><br>

<% @users.each do |user| %>
	<%= link_to user.name, user_page_path(user) %><br>
<% end %>

app/views/pages/user_page.html.erb
<h1>Página del <%= @user.name %></h1>
<br>

<% @category.each do |category| %>
	<% @activities.each do |act| %>
		<% if act.activity.category_id == category.id %>
			<h5><%= category.sustantivo %> que <%= category.past %></h5>
			<% @activities.each do |act| %>
				<% if act.activity.category_id == category.id %>
					<% if act.activity.author %>
						<%= act.activity.name %> de <%= act.activity.author %> | leído el <%= act.start.strftime("%F") %> | registrado <%= time_ago_in_words(act.activity.created_at) %> ago 
						<% if can?(:destroy, act) %>
							<%= link_to 'Editar', edit_activity_path(@user,act.activity.id) %>
							<%= link_to 'Borrar actividad', destroy_activity_path(@user,act.activity.id), method: :delete %>
						<% end %>
					<% else %>
						<%= act.activity.name %> | vista el <%= act.start.strftime("%F") %> | registrado <%= time_ago_in_words(act.activity.created_at) %> ago
						<% if can?(:destroy, act) %>
							<%= link_to 'Editar', edit_activity_path(@user,act.activity.id) %>
							<%= link_to 'Borrar actividad', destroy_activity_path(@user,act.activity.id), method: :delete %>
						<% end %>
					<% end %>
					
					<br>
				<% end %>
			<% end %><br>
			<% break %>
		<% end %>
	<% end %>
<% end %>
		
		