config/routes.rb
Rails.application.routes.draw do
  get 'promote_activities/index'
  get 'pages/index'
  get 'user_page/:user_id', to: 'pages#user_page', as: 'user_page'

  post 'activity/:user_id', to: 'user_activities#create', as: 'asigne_activity'
  get 'edit/:user_id/:activity_id', to: 'user_activities#edit', as: 'edit_activity'
  delete 'activity/:user_id/:activity_id', to: 'user_activities#destroy', as: 'destroy_activity'
  patch 'edit/:user_id/:activity_id', to: 'user_activities#update', as: 'update_activity'

  post 'new_activity/:user_id', to: 'activities#create', as: 'new_activity'
  get 'edit_new_user_activity/:user_id/:activity_id', to: 'activities#edit', as: 'edit_new_user_activity'
  patch 'update_new_activity/:activity_id', to: 'activities#update', as: 'update_new_activity'
  
  get 'promote_activities/:user_id', to: 'promote_activities#index', as: 'promote_activities'
  get 'new_promote', to: 'promote_activities#new', as: 'new_promote'
  post 'create_promote/:user_id', to: 'promote_activities#create', as: 'create_promote'
  delete 'promote/:id', to: 'promote_activities#destroy', as: 'destroy_promote'

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activity, dependent: :destroy
	has_many :users, through: :user_activity

	belongs_to :category, optional: true
	has_many :promote_activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	authorize_resource

	def create
		@activity = Activity.new
		@activity.name = params[:name]
		@activity.save
		@user_activity = UserActivity.new
		@user_activity.user_id = params[:user_id]
		@user_activity.activity_id = @activity.id
		@user_activity.save
		redirect_to edit_new_user_activity_path(current_user,@activity)
	end

	def edit	
		@activity = Activity.where(id: params[:activity_id]).first
	end

	def update
		@activity = Activity.where(id: params[:activity_id]).first
		@activity.update(author: params[:activity][:author])
		@activity.update(category_id: params[:activity][:category_id])
    	redirect_to user_page_path(current_user)
	end
	
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<h2>Editar nueva actividad </h2>
<br>
<% if user_signed_in? %>
	<%= form_with model: Activity, url: update_new_activity_path(@activity), method: :patch, local: true do |f| %>
		
		<%= f.label :author %>
		<%= f.text_field :author %>	<br>

		<%= f.label :category %>
		<%= f.text_field :category_id %>		

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

app/views/activities/edit2.html.erb
<h2>Editar actividad <%= @activity.activity.name %> de <%= @user.name %></h2>


<% if user_signed_in? && can?(:update, @activity) %>
	<%= form_with model: UserActivity, url: update_activity_path(@user), method: :patch, local: true do |f| %>

		<%= f.label :start %>
		<%= f.text_field :start %>		

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

<br><br>