config/routes.rb
Rails.application.routes.draw do
  get 'promote_activities/index'
  get 'pages/index'
  get 'user_page/:user_id', to: 'pages#user_page', as: 'user_page'

  post 'activity/:user_id', to: 'user_activities#create', as: 'asigne_activity'
  get 'edit/:user_id/:activity_id', to: 'user_activities#edit', as: 'edit_activity'
  delete 'activity/:user_id/:activity_id', to: 'user_activities#destroy', as: 'destroy_activity'
  patch 'edit/:user_id/:activity_id', to: 'user_activities#update', as: 'update_activity'

  post 'new_activity/:user_id', to: 'activities#create', as: 'new_activity'
  get 'edit_new_user_activity/:user_id/:activity_id', to: 'activities#edit', as: 'edit_new_user_activity'
  patch 'update_new_activity/:activity_id', to: 'activities#update', as: 'update_new_activity'
  
  get 'promote_activities/:user_id', to: 'promote_activities#index', as: 'promote_activities'
  get 'new_promote', to: 'promote_activities#new', as: 'new_promote'
  post 'create_promote/:user_id', to: 'promote_activities#create', as: 'create_promote'
  delete 'promote/:id', to: 'promote_activities#destroy', as: 'destroy_promote'

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<ul class="nav bg-light">
  <li class="nav-item">
    <%= link_to 'Inicio', root_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <% if user_signed_in? %>
    	<span class="nav-link"><%= current_user.name %></span>
    <% else %>
    	<%= link_to 'Ingresar', new_user_session_path, :class => 'nav-link' %>
    <% end %>
  </li>
  
	<li class="nav-item">
    <% if user_signed_in? %>
      <%= link_to 'Promocionar Actividad', new_promote_path, :class => 'nav-link' %>
    <% end %>
  </li>

  <li class="nav-item">
    <% if user_signed_in? %>
      <%= link_to 'Historial Promociones', promote_activities_path(current_user), :class => 'nav-link' %>
    <% end %>
  </li>

  <li class="nav-item">
		<% if user_signed_in? %>
		  <%= link_to 'Salir', destroy_user_session_path, method: :delete, :class => 'nav-link' %>
		<% else %>
		  <%= link_to 'Registrarse', new_user_registration_path, :class => 'nav-link' %>
		<% end %>
	</li>
  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% if alert.present? %>
      <div class="alert"> <%= alert %></div>
    <% end %>

    <%= yield %>
  </body>
</html>